# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.0
_src_path: gh:algorandfoundation/algokit-puya-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: your@email.tld
author_name: Your Name
contract_name: hello_world
deployment_language: python
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: puya-learn2

